services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: mu3ic
      POSTGRES_PASSWORD: mu3ic
      POSTGRES_DB: mu3ic
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
